### ISSUE TITLE
Package 'brranching' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/Phylogenetics#10]
Package [brranching](https://CRAN.R-project.org/package=brranching) is currently listed in CRAN Task View [Phylogenetics](https://CRAN.R-project.org/view=Phylogenetics) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by willgearty** [comment]
Thanks for the report! I've reached out to the maintainer of 'brranching' to get it restored on CRAN.

**Comment by zeileis** [comment]
Given that there was no follow-up to https://github.com/ropensci/brranching/issues/49 I would recommend to remove the package from the task view now.

**Comment by ms609** [comment]
It looks to me like the package might be restored soon.

The archival reason was "Archived on 2023-02-24 as requires archived package 'phylocomr'", yet I see that 'phylocomr' is now back on CRAN.

I'm not sure whether CRAN automatically return such packages once automated checks execute, or whether maintainer action is needed?

**Comment by zeileis** [comment]
The process to resurrect the package on CRAN has to be triggered by the maintainer - who has to make sure that their own package passes all current checks again.
