### ISSUE TITLE
Package 'apex' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by kurthornik** [cran-task-views/Phylogenetics#11]
Package [apex](https://CRAN.R-project.org/package=apex) is currently listed in CRAN Task View [Phylogenetics](https://CRAN.R-project.org/view=Phylogenetics) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.  See the section on _CRAN package archivals_ in the [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md) for more details.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by ms609** [comment]
I've e-mailed the Thibaut Jombard, who published the package, to see ask what his plans are for the package.

**Comment by willgearty** [comment]
@ms609 I'm guessing you never heard back from Thibaut?

**Comment by ms609** [comment]
Correct – no response yet.

**Comment by willgearty** [comment]
Ah, it looks like @KlausVigo is now [the maintainer of the apex package](https://github.com/thibautjombart/apex/blob/master/DESCRIPTION). Klaus, any plans to restore the apex package to CRAN?

**Comment by KlausVigo** [comment]
Hi all, 
I will submit a new version the next days. It seems with the transfer of the maintainer, Thibaut used an old and not valid email of mine, so I did not get the reminder.
Sorry for the hassle. 
Cheers, 
Klaus

**Comment by KlausVigo** [comment]
@willgearty, I will give it a shot to try to submit it the next days.

**Comment by KlausVigo** [comment]
@willgearty, 
I gave it a shot, submitting it to CRAN. Let's wait and see.
Cheers, 
Klaus

**Comment by KlausVigo** [comment]
@willgearty, 
apex is back aon CRAN.

**Comment by willgearty** [comment]
Fantastic, thanks @KlausVigo !
